import {
  Lecture,
  AnimalType,
  PriceType,
  Category,
  OccupationType,
  Tutor,
  Corporation,
  User,
  GenderType,
  Adoption,
  Abandon,
  Animal,
  AdoptionStatus,
  CurriculumLecture,
  UserCurriculum,
  TraningCenter,
  CurriculumStep,
  Review,
  RatingStatus,
  AttendanceStatus,
} from "@/types/tyeps.all";

const lectureData: Lecture[] = [
  {
    id: "1",
    title: "강형욱 선생님과 함께하는 강아지 배변 훈련!",
    content: `강아지의 다양한 배변 현상, 강형욱 훈련사님의 깊은 내공으로 궁금증 해결!!
      아무렴 강형욱 훈련사와 함께하는 훈련!
      재밌게 즐겨보고 반려견을 더 사랑하세요!!`,
    animal_type: AnimalType.DOG,
    price_type: PriceType.FREE,
    category: Category.TRAINING,
    thumbnailPath: "/Test-courseImg.png",
    videoUrl: "",
    tutor_name: "강형욱",
    tutor_occupation: OccupationType.TRAINER,
    createdAt: new Date(),
    updatedAt: new Date(),
    like: 8,
    tags: ["배변", "훈련"],
    bookmark: true,
    tutorId: "4",
  },
  {
    id: "2",
    title: "강형욱 선생님과 함께하는 강아지 배변 훈련!",
    content: `강아지의 다양한 배변 현상, 강형욱 훈련사님의 깊은 내공으로 궁금증 해결!!
      아무렴 강형욱 훈련사와 함께하는 훈련!
      재밌게 즐겨보고 반려견을 더 사랑하세요!!`,
    animal_type: AnimalType.DOG,
    price_type: PriceType.FREE,
    category: Category.BEAUTY,
    thumbnailPath: "/Test-courseImg.png",
    videoUrl: "",
    tutor_name: "강형욱",
    tutor_occupation: OccupationType.TRAINER,
    createdAt: new Date("2024-8-20"),
    updatedAt: new Date(),
    like: 12,
    tags: ["배변", "훈련", "코카스파니엘"],
    bookmark: true,
    tutorId: "4",
  },
  {
    id: "3",
    title: "강형욱 선생님과 함께하는 강아지 배변 훈련!",
    content: `강아지의 다양한 배변 현상, 강형욱 훈련사님의 깊은 내공으로 궁금증 해결!!
      아무렴 강형욱 훈련사와 함께하는 훈련!
      재밌게 즐겨보고 반려견을 더 사랑하세요!!`,
    animal_type: AnimalType.DOG,
    price_type: PriceType.PAID,
    category: Category.TRAINING,
    thumbnailPath: "/Test-courseImg.png",
    videoUrl: "",
    tutor_name: "강형욱",
    tutor_occupation: OccupationType.TRAINER,
    createdAt: new Date("2024-8-23"),
    updatedAt: new Date(),
    like: 2,
    tags: ["코카스파니엘"],
    bookmark: false,
    tutorId: "4",
  },
  {
    id: "4",
    title: "강형욱 선생님과 함께하는 강아지 배변 훈련!",
    content: `강아지의 다양한 배변 현상, 강형욱 훈련사님의 깊은 내공으로 궁금증 해결!!
    아무렴 강형욱 훈련사와 함께하는 훈련!
    재밌게 즐겨보고 반려견을 더 사랑하세요!!`,
    animal_type: AnimalType.DOG,
    price_type: PriceType.PAID,
    category: Category.COMMUNICATION,
    thumbnailPath: "/Test-courseImg.png",
    videoUrl: "",
    tutor_name: "강형욱",
    tutor_occupation: OccupationType.TRAINER,
    createdAt: new Date("2024-7-23"),
    updatedAt: new Date(),
    like: 1,
    tags: ["코카스파니엘", "사료", "강형욱"],
    bookmark: true,
    tutorId: "4",
  },
  {
    id: "5",
    title: "강형욱 선생님과 함께하는 강아지 배변 훈련!",
    content: `강아지의 다양한 배변 현상, 강형욱 훈련사님의 깊은 내공으로 궁금증 해결!!
      아무렴 강형욱 훈련사와 함께하는 훈련!
      재밌게 즐겨보고 반려견을 더 사랑하세요!!`,
    animal_type: AnimalType.DOG,
    price_type: PriceType.FREE,
    category: Category.COMMUNICATION,
    thumbnailPath: "/Test-courseImg.png",
    videoUrl: "",
    tutor_name: "강형욱",
    tutor_occupation: OccupationType.TRAINER,
    createdAt: new Date(),
    updatedAt: new Date(),
    like: 0,
    tags: ["리트리버", "강형욱"],
    bookmark: false,
    tutorId: "5",
  },
  {
    id: "6",
    title: "강형욱 선생님과 함께하는 강아지 배변 훈련!",
    content:
      "강아지의 다양한 배변 현상, 강형욱 훈련사님의 깊은 내공으로 궁금증 해결!! 강아지의 다양한 배변 현상, 강형욱 훈련사님의 깊은 내공으로 궁금증 해결!!",
    animal_type: AnimalType.CAT,
    price_type: PriceType.FREE,
    category: Category.FOOD,
    thumbnailPath: "/Test-courseImg-cat.png",
    videoUrl: "",
    tutor_name: "강형욱",
    tutor_occupation: OccupationType.TRAINER,
    createdAt: new Date("2024-3-23"),
    updatedAt: new Date(),
    like: 0,
    tags: ["시츄", "강형욱"],
    bookmark: true,
    tutorId: "6",
  },
  {
    id: "7",
    title: "강형욱 선생님과 함께하는 강아지 배변 훈련!",
    content:
      "강아지의 다양한 배변 현상, 강형욱 훈련사님의 깊은 내공으로 궁금증 해결!! 강아지의 다양한 배변 현상, 강형욱 훈련사님의 깊은 내공으로 궁금증 해결!!",
    animal_type: AnimalType.DOG,
    price_type: PriceType.FREE,
    category: Category.FOOD,
    thumbnailPath: "/Test-courseImg.png",
    videoUrl: "",
    tutor_name: "강형욱",
    tutor_occupation: OccupationType.TRAINER,
    createdAt: new Date(),
    updatedAt: new Date(),
    like: 0,
    tags: ["시츄", "강형욱"],
    bookmark: false,
    tutorId: "1",
  },
  {
    id: "8",
    title: "강형욱 선생님과 함께하는 강아지 배변 훈련!",
    content: `강아지의 다양한 배변 현상, 강형욱 훈련사님의 깊은 내공으로 궁금증 해결!!
      아무렴 강형욱 훈련사와 함께하는 훈련!
      재밌게 즐겨보고 반려견을 더 사랑하세요!!`,
    animal_type: AnimalType.CAT,
    price_type: PriceType.FREE,
    category: Category.HEALTH,
    thumbnailPath: "/Test-courseImg-cat.png",
    videoUrl: "",
    tutor_name: "강형욱",
    tutor_occupation: OccupationType.TRAINER,
    createdAt: new Date("2024-8-28"),
    updatedAt: new Date(),
    like: 0,
    tags: ["배변", "훈련", "코카스파니엘", "강형욱"],
    bookmark: true,
    tutorId: "1",
  },
  {
    id: "9",
    title: "강형욱 선생님과 함께하는 강아지 배변 훈련!",
    content: `강아지의 다양한 배변 현상, 강형욱 훈련사님의 깊은 내공으로 궁금증 해결!!
      아무렴 강형욱 훈련사와 함께하는 훈련!
      재밌게 즐겨보고 반려견을 더 사랑하세요!!`,
    animal_type: AnimalType.CAT,
    price_type: PriceType.PAID,
    category: Category.HEALTH,
    thumbnailPath: "/Test-courseImg-cat.png",
    videoUrl: "",
    tutor_name: "강형욱",
    tutor_occupation: OccupationType.TRAINER,
    createdAt: new Date(),
    updatedAt: new Date(),
    like: 0,
    tags: ["시츄"],
    bookmark: false,
    tutorId: "8",
  },
  {
    id: "10",
    title: "강형욱 선생님과 함께하는 강아지 배변 훈련!",
    content:
      "강아지의 고양이 배변 현상, 강형욱 훈련사님의 깊은 내공으로 궁금증 해결!!",
    animal_type: AnimalType.CAT,
    price_type: PriceType.PAID,
    thumbnailPath: "/Test-courseImg-cat.png",
    category: Category.HEALTH,
    videoUrl: "",
    tutor_name: "강형욱",
    tutor_occupation: OccupationType.TRAINER,
    createdAt: new Date(),
    updatedAt: new Date(),
    like: 8,
    tags: ["배변", "훈련", "코카스파니엘"],
    bookmark: true,
    tutorId: "7",
  },
  {
    id: "11",
    title: "강형욱 선생님과 함께하는 강아지 배변 훈련!",
    content:
      "강아지의 고양이 배변 현상, 강형욱 훈련사님의 깊은 내공으로 궁금증 해결!!",
    animal_type: AnimalType.CAT,
    price_type: PriceType.PAID,
    category: Category.PLAY,
    thumbnailPath: "/Test-courseImg-cat.png",
    videoUrl: "",
    tutor_name: "강형욱",
    tutor_occupation: OccupationType.TRAINER,
    createdAt: new Date(),
    updatedAt: new Date(),
    like: 0,
    tags: ["시츄"],
    bookmark: false,
    tutorId: "7",
  },
  {
    id: "12",
    title: "강형욱 선생님과 함께하는 강아지 배변 훈련!",
    content:
      "강아지의 고양이 배변 현상, 강형욱 훈련사님의 깊은 내공으로 궁금증 해결!!",
    animal_type: AnimalType.CAT,
    price_type: PriceType.PAID,
    category: Category.PLAY,
    thumbnailPath: "/Test-courseImg-cat.png",
    videoUrl: "",
    tutor_name: "강형욱",
    tutor_occupation: OccupationType.TRAINER,
    createdAt: new Date(),
    updatedAt: new Date(),
    like: 0,
    tags: ["시츄"],
    bookmark: false,
    tutorId: "7",
  },
  {
    id: "13",
    title: "강형욱 선생님과 함께하는 강아지 배변 훈련!",
    content:
      "강아지의 고양이 배변 현상, 강형욱 훈련사님의 깊은 내공으로 궁금증 해결!!",
    animal_type: AnimalType.CAT,
    price_type: PriceType.PAID,
    category: Category.PLAY,
    thumbnailPath: "/Test-courseImg-cat.png",
    videoUrl: "",
    tutor_name: "강형욱",
    tutor_occupation: OccupationType.TRAINER,
    createdAt: new Date(),
    updatedAt: new Date(),
    like: 0,
    tags: ["시츄"],
    bookmark: false,
    tutorId: "7",
  },
  {
    id: "14",
    title: "강형욱 선생님과 함께하는 강아지 배변 훈련!",
    content:
      "강아지의 고양이 배변 현상, 강형욱 훈련사님의 깊은 내공으로 궁금증 해결!!",
    animal_type: AnimalType.CAT,
    price_type: PriceType.PAID,
    category: Category.PLAY,
    thumbnailPath: "/Test-courseImg-cat.png",
    videoUrl: "",
    tutor_name: "강형욱",
    tutor_occupation: OccupationType.TRAINER,
    createdAt: new Date(),
    updatedAt: new Date(),
    like: 0,
    tags: ["시츄"],
    bookmark: false,
    tutorId: "7",
  },
  {
    id: "15",
    title: "강형욱 선생님과 함께하는 강아지 배변 훈련!",
    content:
      "강아지의 고양이 배변 현상, 강형욱 훈련사님의 깊은 내공으로 궁금증 해결!!",
    animal_type: AnimalType.CAT,
    price_type: PriceType.PAID,
    category: Category.PLAY,
    thumbnailPath: "/Test-courseImg-cat.png",
    videoUrl: "",
    tutor_name: "강형욱",
    tutor_occupation: OccupationType.TRAINER,
    createdAt: new Date(),
    updatedAt: new Date(),
    like: 0,
    tags: ["시츄"],
    bookmark: false,
    tutorId: "7",
  },
  {
    id: "16",
    title: "강형욱 선생님과 함께하는 강아지 배변 훈련!",
    content:
      "강아지의 고양이 배변 현상, 강형욱 훈련사님의 깊은 내공으로 궁금증 해결!!",
    animal_type: AnimalType.CAT,
    price_type: PriceType.PAID,
    category: Category.PLAY,
    thumbnailPath: "/Test-courseImg-cat.png",
    videoUrl: "",
    tutor_name: "강형욱",
    tutor_occupation: OccupationType.TRAINER,
    createdAt: new Date(),
    updatedAt: new Date(),
    like: 0,
    tags: ["시츄"],
    bookmark: false,
    tutorId: "7",
  },
  {
    id: "17",
    title: "강형욱 선생님과 함께하는 강아지 배변 훈련!",
    content:
      "강아지의 고양이 배변 현상, 강형욱 훈련사님의 깊은 내공으로 궁금증 해결!!",
    animal_type: AnimalType.CAT,
    price_type: PriceType.PAID,
    category: Category.PLAY,
    thumbnailPath: "/Test-courseImg-cat.png",
    videoUrl: "",
    tutor_name: "강형욱",
    tutor_occupation: OccupationType.TRAINER,
    createdAt: new Date(),
    updatedAt: new Date(),
    like: 0,
    tags: ["시츄"],
    bookmark: false,
    tutorId: "7",
  },
  {
    id: "18",
    title: "강형욱 선생님과 함께하는 강아지 배변 훈련!",
    content:
      "강아지의 고양이 배변 현상, 강형욱 훈련사님의 깊은 내공으로 궁금증 해결!!",
    animal_type: AnimalType.CAT,
    price_type: PriceType.PAID,
    category: Category.PLAY,
    thumbnailPath: "/Test-courseImg-cat.png",
    videoUrl: "",
    tutor_name: "강형욱",
    tutor_occupation: OccupationType.TRAINER,
    createdAt: new Date(),
    updatedAt: new Date(),
    like: 0,
    tags: ["시츄"],
    bookmark: false,
    tutorId: "7",
  },
  {
    id: "19",
    title: "강형욱 선생님과 함께하는 강아지 배변 훈련!",
    content:
      "강아지의 고양이 배변 현상, 강형욱 훈련사님의 깊은 내공으로 궁금증 해결!!",
    animal_type: AnimalType.CAT,
    price_type: PriceType.PAID,
    category: Category.PLAY,
    thumbnailPath: "/Test-courseImg-cat.png",
    videoUrl: "",
    tutor_name: "강형욱",
    tutor_occupation: OccupationType.TRAINER,
    createdAt: new Date(),
    updatedAt: new Date(),
    like: 0,
    tags: ["시츄"],
    bookmark: false,
    tutorId: "7",
  },
  {
    id: "20",
    title: "강형욱 선생님과 함께하는 강아지 배변 훈련!",
    content:
      "강아지의 고양이 배변 현상, 강형욱 훈련사님의 깊은 내공으로 궁금증 해결!!",
    animal_type: AnimalType.DOG,
    price_type: PriceType.PAID,
    category: Category.PLAY,
    thumbnailPath: "/Test-courseImg.png",
    videoUrl: "",
    tutor_name: "강형욱",
    tutor_occupation: OccupationType.TRAINER,
    createdAt: new Date(),
    updatedAt: new Date(),
    like: 0,
    tags: ["시츄"],
    bookmark: false,
    tutorId: "7",
  },
  {
    id: "21",
    title: "강형욱 선생님과 함께하는 강아지 배변 훈련!",
    content:
      "강아지의 고양이 배변 현상, 강형욱 훈련사님의 깊은 내공으로 궁금증 해결!!",
    animal_type: AnimalType.DOG,
    price_type: PriceType.PAID,
    category: Category.PLAY,
    thumbnailPath: "/Test-courseImg.png",
    videoUrl: "",
    tutor_name: "강형욱",
    tutor_occupation: OccupationType.TRAINER,
    createdAt: new Date(),
    updatedAt: new Date(),
    like: 0,
    tags: ["시츄"],
    bookmark: false,
    tutorId: "7",
  },
  {
    id: "22",
    title: "강형욱 선생님과 함께하는 강아지 배변 훈련!",
    content:
      "강아지의 고양이 배변 현상, 강형욱 훈련사님의 깊은 내공으로 궁금증 해결!!",
    animal_type: AnimalType.CAT,
    price_type: PriceType.PAID,
    category: Category.PLAY,
    thumbnailPath: "/Test-courseImg-cat.png",
    videoUrl: "",
    tutor_name: "강형욱",
    tutor_occupation: OccupationType.TRAINER,
    createdAt: new Date(),
    updatedAt: new Date(),
    like: 0,
    tags: ["시츄"],
    bookmark: false,
    tutorId: "7",
  },
  {
    id: "23",
    title: "강형욱 선생님과 함께하는 강아지 배변 훈련!",
    content:
      "강아지의 고양이 배변 현상, 강형욱 훈련사님의 깊은 내공으로 궁금증 해결!!",
    animal_type: AnimalType.CAT,
    price_type: PriceType.PAID,
    category: Category.PLAY,
    thumbnailPath: "/Test-courseImg-cat.png",
    videoUrl: "",
    tutor_name: "강형욱",
    tutor_occupation: OccupationType.TRAINER,
    createdAt: new Date(),
    updatedAt: new Date(),
    like: 0,
    tags: ["시츄"],
    bookmark: false,
    tutorId: "7",
  },
  {
    id: "24",
    title: "강형욱 선생님과 함께하는 강아지 배변 훈련!",
    content:
      "강아지의 고양이 배변 현상, 강형욱 훈련사님의 깊은 내공으로 궁금증 해결!!",
    animal_type: AnimalType.CAT,
    price_type: PriceType.PAID,
    category: Category.PLAY,
    thumbnailPath: "/Test-courseImg-cat.png",
    videoUrl: "",
    tutor_name: "강형욱",
    tutor_occupation: OccupationType.TRAINER,
    createdAt: new Date(),
    updatedAt: new Date(),
    like: 0,
    tags: ["시츄"],
    bookmark: false,
    tutorId: "7",
  },
  {
    id: "25",
    title: "강형욱 선생님과 함께하는 강아지 배변 훈련!",
    content:
      "강아지의 고양이 배변 현상, 강형욱 훈련사님의 깊은 내공으로 궁금증 해결!!",
    animal_type: AnimalType.CAT,
    price_type: PriceType.PAID,
    category: Category.PLAY,
    thumbnailPath: "/Test-courseImg-cat.png",
    videoUrl: "",
    tutor_name: "강형욱",
    tutor_occupation: OccupationType.TRAINER,
    createdAt: new Date(),
    updatedAt: new Date(),
    like: 0,
    tags: ["시츄"],
    bookmark: false,
    tutorId: "7",
  },
  {
    id: "26",
    title: "강형욱 선생님과 함께하는 강아지 배변 훈련!",
    content:
      "강아지의 고양이 배변 현상, 강형욱 훈련사님의 깊은 내공으로 궁금증 해결!!",
    animal_type: AnimalType.CAT,
    price_type: PriceType.PAID,
    category: Category.PLAY,
    thumbnailPath: "/Test-courseImg-cat.png",
    videoUrl: "",
    tutor_name: "강형욱",
    tutor_occupation: OccupationType.TRAINER,
    createdAt: new Date(),
    updatedAt: new Date(),
    like: 0,
    tags: ["시츄"],
    bookmark: false,
    tutorId: "7",
  },
  {
    id: "27",
    title: "강형욱 선생님과 함께하는 강아지 배변 훈련!",
    content:
      "강아지의 고양이 배변 현상, 강형욱 훈련사님의 깊은 내공으로 궁금증 해결!!",
    animal_type: AnimalType.CAT,
    price_type: PriceType.PAID,
    category: Category.PLAY,
    thumbnailPath: "/Test-courseImg-cat.png",
    videoUrl: "",
    tutor_name: "강형욱",
    tutor_occupation: OccupationType.TRAINER,
    createdAt: new Date(),
    updatedAt: new Date(),
    like: 0,
    tags: ["시츄"],
    bookmark: false,
    tutorId: "7",
  },
  {
    id: "28",
    title: "강형욱 선생님과 함께하는 강아지 배변 훈련!",
    content:
      "강아지의 고양이 배변 현상, 강형욱 훈련사님의 깊은 내공으로 궁금증 해결!!",
    animal_type: AnimalType.CAT,
    price_type: PriceType.PAID,
    category: Category.PLAY,
    thumbnailPath: "/Test-courseImg-cat.png",
    videoUrl: "",
    tutor_name: "강형욱",
    tutor_occupation: OccupationType.TRAINER,
    createdAt: new Date(),
    updatedAt: new Date(),
    like: 0,
    tags: ["시츄"],
    bookmark: false,
    tutorId: "7",
  },
  {
    id: "29",
    title: "강형욱 선생님과 함께하는 강아지 배변 훈련!",
    content:
      "강아지의 고양이 배변 현상, 강형욱 훈련사님의 깊은 내공으로 궁금증 해결!!",
    animal_type: AnimalType.CAT,
    price_type: PriceType.PAID,
    category: Category.PLAY,
    thumbnailPath: "/Test-courseImg-cat.png",
    videoUrl: "",
    tutor_name: "강형욱",
    tutor_occupation: OccupationType.TRAINER,
    createdAt: new Date(),
    updatedAt: new Date(),
    like: 0,
    tags: ["시츄"],
    bookmark: false,
    tutorId: "7",
  },
  {
    id: "30",
    title: "강형욱 선생님과 함께하는 강아지 배변 훈련!",
    content:
      "강아지의 고양이 배변 현상, 강형욱 훈련사님의 깊은 내공으로 궁금증 해결!!",
    animal_type: AnimalType.CAT,
    price_type: PriceType.PAID,
    category: Category.PLAY,
    thumbnailPath: "/Test-courseImg-cat.png",
    videoUrl: "",
    tutor_name: "강형욱",
    tutor_occupation: OccupationType.TRAINER,
    createdAt: new Date(),
    updatedAt: new Date(),
    like: 0,
    tags: ["시츄"],
    bookmark: false,
    tutorId: "7",
  },
  {
    id: "31",
    title: "강형욱 선생님과 함께하는 강아지 배변 훈련!",
    content:
      "강아지의 고양이 배변 현상, 강형욱 훈련사님의 깊은 내공으로 궁금증 해결!!",
    animal_type: AnimalType.CAT,
    price_type: PriceType.PAID,
    category: Category.PLAY,
    thumbnailPath: "/Test-courseImg-cat.png",
    videoUrl: "",
    tutor_name: "강형욱",
    tutor_occupation: OccupationType.TRAINER,
    createdAt: new Date(),
    updatedAt: new Date(),
    like: 0,
    tags: ["시츄"],
    bookmark: false,
    tutorId: "7",
  },
  {
    id: "32",
    title: "강형욱 선생님과 함께하는 강아지 배변 훈련!",
    content:
      "강아지의 고양이 배변 현상, 강형욱 훈련사님의 깊은 내공으로 궁금증 해결!!",
    animal_type: AnimalType.CAT,
    price_type: PriceType.PAID,
    category: Category.PLAY,
    thumbnailPath: "/Test-courseImg-cat.png",
    videoUrl: "",
    tutor_name: "강형욱",
    tutor_occupation: OccupationType.TRAINER,
    createdAt: new Date(),
    updatedAt: new Date(),
    like: 0,
    tags: ["시츄"],
    bookmark: false,
    tutorId: "7",
  },
];

const curriculumLectureData: CurriculumLecture[] = [
  {
    id: "1",
    index: 1,
    title: "강형욱 선생님과 함께하는 강아지 배변 훈련!",
    content: `강아지의 다양한 배변 현상, 강형욱 훈련사님의 깊은 내공으로 궁금증 해결!!
      아무렴 강형욱 훈련사와 함께하는 훈련!
      재밌게 즐겨보고 반려견을 더 사랑하세요!!`,
    animal_type: AnimalType.DOG,
    category: Category.TRAINING,
    thumbnailPath: "/Test-courseImg.png",
    videoUrl: "",
    tutor_name: "강형욱",
    tutor_occupation: OccupationType.TRAINER,
    createdAt: new Date(),
    updatedAt: new Date(),
    curriculumCollectionId: "2",
    tutorId: "4",
  },
  {
    id: "2",
    index: 1,
    title: "강형욱 선생님과 함께하는 강아지 배변 훈련!",
    content: `강아지의 다양한 배변 현상, 강형욱 훈련사님의 깊은 내공으로 궁금증 해결!!
      아무렴 강형욱 훈련사와 함께하는 훈련!
      재밌게 즐겨보고 반려견을 더 사랑하세요!!`,
    animal_type: AnimalType.DOG,
    category: Category.BEAUTY,
    thumbnailPath: "/Test-courseImg.png",
    videoUrl: "",
    tutor_name: "강형욱",
    tutor_occupation: OccupationType.TRAINER,
    createdAt: new Date("2024-8-20"),
    updatedAt: new Date(),
    curriculumCollectionId: "2",
    tutorId: "4",
  },
  {
    id: "3",
    index: 2,
    title: "강형욱 선생님과 함께하는 강아지 배변 훈련!",
    content: `강아지의 다양한 배변 현상, 강형욱 훈련사님의 깊은 내공으로 궁금증 해결!!
      아무렴 강형욱 훈련사와 함께하는 훈련!
      재밌게 즐겨보고 반려견을 더 사랑하세요!!`,
    animal_type: AnimalType.DOG,
    category: Category.TRAINING,
    thumbnailPath: "/Test-courseImg.png",
    videoUrl: "",
    tutor_name: "강형욱",
    tutor_occupation: OccupationType.TRAINER,
    createdAt: new Date("2024-8-23"),
    updatedAt: new Date(),
    curriculumCollectionId: "2",
    tutorId: "4",
  },
  {
    id: "4",
    index: 1,
    title: "강형욱 선생님과 함께하는 강아지 배변 훈련!",
    content: `강아지의 다양한 배변 현상, 강형욱 훈련사님의 깊은 내공으로 궁금증 해결!!
    아무렴 강형욱 훈련사와 함께하는 훈련!
    재밌게 즐겨보고 반려견을 더 사랑하세요!!`,
    animal_type: AnimalType.DOG,
    category: Category.COMMUNICATION,
    thumbnailPath: "/Test-courseImg.png",
    videoUrl: "",
    tutor_name: "강형욱",
    tutor_occupation: OccupationType.TRAINER,
    createdAt: new Date("2024-7-23"),
    updatedAt: new Date(),
    curriculumCollectionId: "2",
    tutorId: "4",
  },
  {
    id: "5",
    index: 2,
    title: "강형욱 선생님과 함께하는 강아지 배변 훈련!",
    content: `강아지의 다양한 배변 현상, 강형욱 훈련사님의 깊은 내공으로 궁금증 해결!!
      아무렴 강형욱 훈련사와 함께하는 훈련!
      재밌게 즐겨보고 반려견을 더 사랑하세요!!`,
    animal_type: AnimalType.DOG,
    category: Category.COMMUNICATION,
    thumbnailPath: "/Test-courseImg.png",
    videoUrl: "",
    tutor_name: "강형욱",
    tutor_occupation: OccupationType.TRAINER,
    createdAt: new Date(),
    updatedAt: new Date(),
    curriculumCollectionId: "2",
    tutorId: "5",
  },
  {
    id: "6",
    index: 2,
    title: "강형욱 선생님과 함께하는 강아지 배변 훈련!",
    content:
      "강아지의 다양한 배변 현상, 강형욱 훈련사님의 깊은 내공으로 궁금증 해결!! 강아지의 다양한 배변 현상, 강형욱 훈련사님의 깊은 내공으로 궁금증 해결!!",
    animal_type: AnimalType.CAT,
    category: Category.BEAUTY,
    thumbnailPath: "/Test-courseImg-cat.png",
    videoUrl: "",
    tutor_name: "강형욱",
    tutor_occupation: OccupationType.TRAINER,
    createdAt: new Date("2024-3-23"),
    updatedAt: new Date(),
    curriculumCollectionId: "2",
    tutorId: "6",
  },
  {
    id: "7",
    index: 3,
    title: "강형욱 선생님과 함께하는 강아지 배변 훈련!",
    content: `강아지의 다양한 배변 현상, 강형욱 훈련사님의 깊은 내공으로 궁금증 해결!!
      아무렴 강형욱 훈련사와 함께하는 훈련!
      재밌게 즐겨보고 반려견을 더 사랑하세요!!`,
    animal_type: AnimalType.DOG,
    category: Category.TRAINING,
    thumbnailPath: "/Test-courseImg.png",
    videoUrl: "",
    tutor_name: "강형욱",
    tutor_occupation: OccupationType.TRAINER,
    createdAt: new Date(),
    updatedAt: new Date(),
    curriculumCollectionId: "2",
    tutorId: "4",
  },
  {
    id: "8",
    index: 4,
    title: "강형욱 선생님과 함께하는 강아지 배변 훈련!",
    content: `강아지의 다양한 배변 현상, 강형욱 훈련사님의 깊은 내공으로 궁금증 해결!!
      아무렴 강형욱 훈련사와 함께하는 훈련!
      재밌게 즐겨보고 반려견을 더 사랑하세요!!`,
    animal_type: AnimalType.DOG,
    category: Category.TRAINING,
    thumbnailPath: "/Test-courseImg.png",
    videoUrl: "",
    tutor_name: "강형욱",
    tutor_occupation: OccupationType.TRAINER,
    createdAt: new Date(),
    updatedAt: new Date(),
    curriculumCollectionId: "2",
    tutorId: "4",
  },
  {
    id: "9",
    index: 5,
    title: "강형욱 선생님과 함께하는 강아지 배변 훈련!",
    content: `강아지의 다양한 배변 현상, 강형욱 훈련사님의 깊은 내공으로 궁금증 해결!!
      아무렴 강형욱 훈련사와 함께하는 훈련!
      재밌게 즐겨보고 반려견을 더 사랑하세요!!`,
    animal_type: AnimalType.DOG,
    category: Category.TRAINING,
    thumbnailPath: "/Test-courseImg.png",
    videoUrl: "",
    tutor_name: "강형욱",
    tutor_occupation: OccupationType.TRAINER,
    createdAt: new Date(),
    updatedAt: new Date(),
    curriculumCollectionId: "2",
    tutorId: "4",
  },
  {
    id: "10",
    index: 6,
    title: "강형욱 선생님과 함께하는 강아지 배변 훈련!",
    content: `강아지의 다양한 배변 현상, 강형욱 훈련사님의 깊은 내공으로 궁금증 해결!!
      아무렴 강형욱 훈련사와 함께하는 훈련!
      재밌게 즐겨보고 반려견을 더 사랑하세요!!`,
    animal_type: AnimalType.DOG,
    category: Category.TRAINING,
    thumbnailPath: "/Test-courseImg.png",
    videoUrl: "",
    tutor_name: "강형욱",
    tutor_occupation: OccupationType.TRAINER,
    createdAt: new Date(),
    updatedAt: new Date(),
    curriculumCollectionId: "2",
    tutorId: "4",
  },
  {
    id: "11",
    index: 7,
    title: "강형욱 선생님과 함께하는 강아지 배변 훈련!",
    content: `강아지의 다양한 배변 현상, 강형욱 훈련사님의 깊은 내공으로 궁금증 해결!!
      아무렴 강형욱 훈련사와 함께하는 훈련!
      재밌게 즐겨보고 반려견을 더 사랑하세요!!`,
    animal_type: AnimalType.DOG,
    category: Category.TRAINING,
    thumbnailPath: "/Test-courseImg.png",
    videoUrl: "",
    tutor_name: "강형욱",
    tutor_occupation: OccupationType.TRAINER,
    createdAt: new Date(),
    updatedAt: new Date(),
    curriculumCollectionId: "2",
    tutorId: "4",
  },
  {
    id: "12",
    index: 8,
    title: "강형욱 선생님과 함께하는 강아지 배변 훈련!",
    content: `강아지의 다양한 배변 현상, 강형욱 훈련사님의 깊은 내공으로 궁금증 해결!!
      아무렴 강형욱 훈련사와 함께하는 훈련!
      재밌게 즐겨보고 반려견을 더 사랑하세요!!`,
    animal_type: AnimalType.DOG,
    category: Category.TRAINING,
    thumbnailPath: "/Test-courseImg.png",
    videoUrl: "",
    tutor_name: "강형욱",
    tutor_occupation: OccupationType.TRAINER,
    createdAt: new Date(),
    updatedAt: new Date(),
    curriculumCollectionId: "2",
    tutorId: "4",
  },
  {
    id: "13",
    index: 3,
    title: "강형욱 선생님과 함께하는 강아지 배변 훈련!",
    content: `강아지의 다양한 배변 현상, 강형욱 훈련사님의 깊은 내공으로 궁금증 해결!!
      아무렴 강형욱 훈련사와 함께하는 훈련!
      재밌게 즐겨보고 반려견을 더 사랑하세요!!`,
    animal_type: AnimalType.DOG,
    category: Category.BEAUTY,
    thumbnailPath: "/Test-courseImg.png",
    videoUrl: "",
    tutor_name: "강형욱",
    tutor_occupation: OccupationType.TRAINER,
    createdAt: new Date("2024-8-20"),
    updatedAt: new Date(),
    curriculumCollectionId: "2",
    tutorId: "4",
  },
  {
    id: "14",
    index: 4,
    title: "강형욱 선생님과 함께하는 강아지 배변 훈련!",
    content: `강아지의 다양한 배변 현상, 강형욱 훈련사님의 깊은 내공으로 궁금증 해결!!
      아무렴 강형욱 훈련사와 함께하는 훈련!
      재밌게 즐겨보고 반려견을 더 사랑하세요!!`,
    animal_type: AnimalType.DOG,
    category: Category.BEAUTY,
    thumbnailPath: "/Test-courseImg.png",
    videoUrl: "",
    tutor_name: "강형욱",
    tutor_occupation: OccupationType.TRAINER,
    createdAt: new Date("2024-8-20"),
    updatedAt: new Date(),
    curriculumCollectionId: "2",
    tutorId: "4",
  },
  {
    id: "15",
    index: 5,
    title: "강형욱 선생님과 함께하는 강아지 배변 훈련!",
    content: `강아지의 다양한 배변 현상, 강형욱 훈련사님의 깊은 내공으로 궁금증 해결!!
      아무렴 강형욱 훈련사와 함께하는 훈련!
      재밌게 즐겨보고 반려견을 더 사랑하세요!!`,
    animal_type: AnimalType.DOG,
    category: Category.BEAUTY,
    thumbnailPath: "/Test-courseImg.png",
    videoUrl: "",
    tutor_name: "강형욱",
    tutor_occupation: OccupationType.TRAINER,
    createdAt: new Date("2024-8-20"),
    updatedAt: new Date(),
    curriculumCollectionId: "2",
    tutorId: "4",
  },
  {
    id: "16",
    index: 6,
    title: "강형욱 선생님과 함께하는 강아지 배변 훈련!",
    content: `강아지의 다양한 배변 현상, 강형욱 훈련사님의 깊은 내공으로 궁금증 해결!!
      아무렴 강형욱 훈련사와 함께하는 훈련!
      재밌게 즐겨보고 반려견을 더 사랑하세요!!`,
    animal_type: AnimalType.DOG,
    category: Category.BEAUTY,
    thumbnailPath: "/Test-courseImg.png",
    videoUrl: "",
    tutor_name: "강형욱",
    tutor_occupation: OccupationType.TRAINER,
    createdAt: new Date("2024-8-20"),
    updatedAt: new Date(),
    curriculumCollectionId: "2",
    tutorId: "4",
  },
  {
    id: "17",
    index: 7,
    title: "강형욱 선생님과 함께하는 강아지 배변 훈련!",
    content: `강아지의 다양한 배변 현상, 강형욱 훈련사님의 깊은 내공으로 궁금증 해결!!
      아무렴 강형욱 훈련사와 함께하는 훈련!
      재밌게 즐겨보고 반려견을 더 사랑하세요!!`,
    animal_type: AnimalType.DOG,
    category: Category.BEAUTY,
    thumbnailPath: "/Test-courseImg.png",
    videoUrl: "",
    tutor_name: "강형욱",
    tutor_occupation: OccupationType.TRAINER,
    createdAt: new Date("2024-8-20"),
    updatedAt: new Date(),
    curriculumCollectionId: "2",
    tutorId: "4",
  },
  {
    id: "18",
    index: 8,
    title: "강형욱 선생님과 함께하는 강아지 배변 훈련!",
    content: `강아지의 다양한 배변 현상, 강형욱 훈련사님의 깊은 내공으로 궁금증 해결!!
      아무렴 강형욱 훈련사와 함께하는 훈련!
      재밌게 즐겨보고 반려견을 더 사랑하세요!!`,
    animal_type: AnimalType.DOG,
    category: Category.BEAUTY,
    thumbnailPath: "/Test-courseImg.png",
    videoUrl: "",
    tutor_name: "강형욱",
    tutor_occupation: OccupationType.TRAINER,
    createdAt: new Date("2024-8-20"),
    updatedAt: new Date(),
    curriculumCollectionId: "2",
    tutorId: "4",
  },
  {
    id: "19",
    index: 3,
    title: "강형욱 선생님과 함께하는 강아지 배변 훈련!",
    content: `강아지의 다양한 배변 현상, 강형욱 훈련사님의 깊은 내공으로 궁금증 해결!!
    아무렴 강형욱 훈련사와 함께하는 훈련!
    재밌게 즐겨보고 반려견을 더 사랑하세요!!`,
    animal_type: AnimalType.DOG,
    category: Category.COMMUNICATION,
    thumbnailPath: "/Test-courseImg.png",
    videoUrl: "",
    tutor_name: "강형욱",
    tutor_occupation: OccupationType.TRAINER,
    createdAt: new Date("2024-7-23"),
    updatedAt: new Date(),
    curriculumCollectionId: "2",
    tutorId: "4",
  },
  {
    id: "20",
    index: 4,
    title: "강형욱 선생님과 함께하는 강아지 배변 훈련!",
    content: `강아지의 다양한 배변 현상, 강형욱 훈련사님의 깊은 내공으로 궁금증 해결!!
    아무렴 강형욱 훈련사와 함께하는 훈련!
    재밌게 즐겨보고 반려견을 더 사랑하세요!!`,
    animal_type: AnimalType.DOG,
    category: Category.COMMUNICATION,
    thumbnailPath: "/Test-courseImg.png",
    videoUrl: "",
    tutor_name: "강형욱",
    tutor_occupation: OccupationType.TRAINER,
    createdAt: new Date("2024-7-23"),
    updatedAt: new Date(),
    curriculumCollectionId: "2",
    tutorId: "4",
  },
  {
    id: "21",
    index: 5,
    title: "강형욱 선생님과 함께하는 강아지 배변 훈련!",
    content: `강아지의 다양한 배변 현상, 강형욱 훈련사님의 깊은 내공으로 궁금증 해결!!
    아무렴 강형욱 훈련사와 함께하는 훈련!
    재밌게 즐겨보고 반려견을 더 사랑하세요!!`,
    animal_type: AnimalType.DOG,
    category: Category.COMMUNICATION,
    thumbnailPath: "/Test-courseImg.png",
    videoUrl: "",
    tutor_name: "강형욱",
    tutor_occupation: OccupationType.TRAINER,
    createdAt: new Date("2024-7-23"),
    updatedAt: new Date(),
    curriculumCollectionId: "2",
    tutorId: "4",
  },
  {
    id: "22",
    index: 6,
    title: "강형욱 선생님과 함께하는 강아지 배변 훈련!",
    content: `강아지의 다양한 배변 현상, 강형욱 훈련사님의 깊은 내공으로 궁금증 해결!!
    아무렴 강형욱 훈련사와 함께하는 훈련!
    재밌게 즐겨보고 반려견을 더 사랑하세요!!`,
    animal_type: AnimalType.DOG,
    category: Category.COMMUNICATION,
    thumbnailPath: "/Test-courseImg.png",
    videoUrl: "",
    tutor_name: "강형욱",
    tutor_occupation: OccupationType.TRAINER,
    createdAt: new Date("2024-7-23"),
    updatedAt: new Date(),
    curriculumCollectionId: "2",
    tutorId: "4",
  },
  {
    id: "23",
    index: 7,
    title: "강형욱 선생님과 함께하는 강아지 배변 훈련!",
    content: `강아지의 다양한 배변 현상, 강형욱 훈련사님의 깊은 내공으로 궁금증 해결!!
    아무렴 강형욱 훈련사와 함께하는 훈련!
    재밌게 즐겨보고 반려견을 더 사랑하세요!!`,
    animal_type: AnimalType.DOG,
    category: Category.COMMUNICATION,
    thumbnailPath: "/Test-courseImg.png",
    videoUrl: "",
    tutor_name: "강형욱",
    tutor_occupation: OccupationType.TRAINER,
    createdAt: new Date("2024-7-23"),
    updatedAt: new Date(),
    curriculumCollectionId: "2",
    tutorId: "4",
  },
  {
    id: "24",
    index: 8,
    title: "강형욱 선생님과 함께하는 강아지 배변 훈련!",
    content: `강아지의 다양한 배변 현상, 강형욱 훈련사님의 깊은 내공으로 궁금증 해결!!
    아무렴 강형욱 훈련사와 함께하는 훈련!
    재밌게 즐겨보고 반려견을 더 사랑하세요!!`,
    animal_type: AnimalType.DOG,
    category: Category.COMMUNICATION,
    thumbnailPath: "/Test-courseImg.png",
    videoUrl: "",
    tutor_name: "강형욱",
    tutor_occupation: OccupationType.TRAINER,
    createdAt: new Date("2024-7-23"),
    updatedAt: new Date(),
    curriculumCollectionId: "2",
    tutorId: "4",
  },
];

const userCurriculumData: UserCurriculum[] = [
  {
    id: "1",
    curriculumType: AnimalType.DOG,
    curriculumStep: CurriculumStep.LECTURE,
    currentCategory: Category.TRAINING,
    attendances: null,
    currentIndex: 2,
    userId: "1",
  },
  {
    id: "2",
    curriculumType: AnimalType.DOG,
    curriculumStep: CurriculumStep.LECTURE_END,
    currentCategory: Category.TRAINING,
    attendances: [
      {
        training_date: new Date("2024-10-15"),
        start_time: "13:00",
        end_time: "18:00",
        attendance_status: AttendanceStatus.ABSENT,
        absent_reason: "그냥",
      },
      {
        training_date: new Date("2024-10-17"),
        start_time: "13:00",
        end_time: "18:00",
        attendance_status: AttendanceStatus.ABSENT,
        absent_reason: "그냥",
      },
      {
        training_date: new Date("2024-10-21"),
        start_time: "13:00",
        end_time: "18:00",
        attendance_status: AttendanceStatus.ABSENT,
        absent_reason: "그냥",
      },
      {
        training_date: new Date("2024-10-25"),
        start_time: "13:00",
        end_time: "18:00",
        attendance_status: AttendanceStatus.ATTENDANCE,
        absent_reason: null,
      },
      {
        training_date: new Date("2024-11-2"),
        start_time: "13:00",
        end_time: "18:00",
        attendance_status: AttendanceStatus.ATTENDANCE,
        absent_reason: null,
      },
      {
        training_date: new Date("2024-11-12"),
        start_time: "16:00",
        end_time: "18:00",
        attendance_status: AttendanceStatus.TARDY,
        absent_reason: null,
      },
      {
        training_date: new Date("2024-11-21"),
        start_time: "13:00",
        end_time: "18:00",
        attendance_status: AttendanceStatus.SCHEDULED,
        absent_reason: null,
      },
    ],
    currentIndex: 2,
    userId: "2",
  },
  {
    id: "3",
    curriculumType: AnimalType.DOG,
    curriculumStep: CurriculumStep.TRANING,
    currentCategory: Category.BEAUTY,
    attendances: [
      {
        training_date: new Date("2024-10-15"),
        start_time: "13:00",
        end_time: "18:00",
        attendance_status: AttendanceStatus.ABSENT,
        absent_reason: "그냥 아파서 안 나옵ㄴ니다. 다음부터는 꼭 참석해주세요.",
      },
      {
        training_date: new Date("2024-10-17"),
        start_time: "13:00",
        end_time: "18:00",
        attendance_status: AttendanceStatus.ABSENT,
        absent_reason: "그냥 아파서 안 나옵ㄴ니다. 다음부터는 꼭 참석해주세요.",
      },
      {
        training_date: new Date("2024-10-21"),
        start_time: "13:00",
        end_time: "18:00",
        attendance_status: AttendanceStatus.ABSENT,
        absent_reason: "그냥 아파서 안 나옵ㄴ니다. 다음부터는 꼭 참석해주세요.",
      },
      {
        training_date: new Date("2024-10-25"),
        start_time: "13:00",
        end_time: "18:00",
        attendance_status: AttendanceStatus.ATTENDANCE,
        absent_reason: null,
      },
      {
        training_date: new Date("2024-11-2"),
        start_time: "13:00",
        end_time: "18:00",
        attendance_status: AttendanceStatus.ATTENDANCE,
        absent_reason: null,
      },
      {
        training_date: new Date("2024-11-12"),
        start_time: "16:00",
        end_time: "18:00",
        attendance_status: AttendanceStatus.TARDY,
        absent_reason: null,
      },
      {
        training_date: new Date("2024-11-21"),
        start_time: "13:00",
        end_time: "18:00",
        attendance_status: AttendanceStatus.SCHEDULED,
        absent_reason: null,
      },
    ],
    currentIndex: 2,
    userId: "3",
  },
];

const TutorData: Tutor[] = [
  {
    id: "1",
    name: "강형욱",
    introduction: `안녕하세요. 강형욱입니다.
    안녕하세요, 저는 동물들을 사랑하고 그들의 건강을 책임지는 수의사입니다.
    다양한 동물들의 질병을 진단하고 치료하며, 반려동물과 그 가족들에게 최상의 케어를 제공하기 위해 항상 노력하고 있습니다.
    동물들이 건강하고 행복하게 지낼 수 있도록 돕는 것이 저의 가장 큰 보람입니다.`,
    profile_img: "/Test-face.png",
    career: "보듬컴퍼니 훈련사", // 최종(현재) 커리어
    occupation: OccupationType.TRAINER,
    traning_name: "보듬 훈련소",
    corporation_name: "보듬컴퍼니",
    traning_location: "중랑구 상봉동 104-37",
    corporationId: "1",
    createdAt: new Date("2024-7-23"),
    updatedAt: new Date(),
  },
  {
    id: "2",
    name: "강형욱",
    introduction: "안녕하세요. 강형욱입니다.",
    profile_img: "/Test-face.png",
    career: "보듬컴퍼니 훈련사", // 최종(현재) 커리어
    occupation: OccupationType.TRAINER,
    traning_name: "보듬 훈련소",
    corporation_name: "보듬컴퍼니",
    traning_location: "중랑구 상봉동 104-37",
    corporationId: "1",
    createdAt: new Date("2024-7-23"),
    updatedAt: new Date(),
  },
  {
    id: "3",
    name: "강형욱",
    introduction: "안녕하세요. 강형욱입니다.",
    profile_img: "/Test-face.png",
    career: "보듬컴퍼니 훈련사", // 최종(현재) 커리어
    occupation: OccupationType.TRAINER,
    traning_name: "보듬 훈련소",
    corporation_name: "보듬컴퍼니",
    traning_location: "중랑구 상봉동 104-37",
    corporationId: "1",
    createdAt: new Date("2024-7-23"),
    updatedAt: new Date(),
  },
  {
    id: "4",
    name: "강형욱",
    introduction: `안녕하세요. 강형욱입니다.
    안녕하세요, 저는 동물들을 사랑하고 그들의 건강을 책임지는 수의사입니다.
    다양한 동물들의 질병을 진단하고 치료하며, 반려동물과 그 가족들에게 최상의 케어를 제공하기 위해 항상 노력하고 있습니다.
    동물들이 건강하고 행복하게 지낼 수 있도록 돕는 것이 저의 가장 큰 보람입니다.`,
    profile_img: "/Test-face.png",
    career: "보듬컴퍼니 훈련사", // 최종(현재) 커리어
    occupation: OccupationType.TRAINER,
    traning_name: "보듬 훈련소",
    corporation_name: "보듬컴퍼니",
    traning_location: "중랑구 상봉동 104-37",
    corporationId: "1",
    createdAt: new Date("2024-7-23"),
    updatedAt: new Date(),
  },
  {
    id: "5",
    name: "강형욱",
    introduction: "안녕하세요. 강형욱입니다.",
    profile_img: "/Test-face.png",
    career: "보듬컴퍼니 훈련사", // 최종(현재) 커리어
    occupation: OccupationType.TRAINER,
    traning_name: "보듬 훈련소",
    corporation_name: "보듬컴퍼니",
    traning_location: "중랑구 상봉동 104-37",
    corporationId: "1",
    createdAt: new Date("2024-7-23"),
    updatedAt: new Date(),
  },
  {
    id: "6",
    name: "강형욱",
    introduction: `안녕하세요. 강형욱입니다.
    안녕하세요, 저는 동물들을 사랑하고 그들의 건강을 책임지는 수의사입니다.
    다양한 동물들의 질병을 진단하고 치료하며, 반려동물과 그 가족들에게 최상의 케어를 제공하기 위해 항상 노력하고 있습니다.
    동물들이 건강하고 행복하게 지낼 수 있도록 돕는 것이 저의 가장 큰 보람입니다.`,
    profile_img: "/Test-face.png",
    career: "보듬컴퍼니 훈련사", // 최종(현재) 커리어
    occupation: OccupationType.TRAINER,
    traning_name: "보듬 훈련소",
    corporation_name: "보듬컴퍼니",
    traning_location: "중랑구 상봉동 104-37",
    corporationId: "4",
    createdAt: new Date("2024-7-23"),
    updatedAt: new Date(),
  },

  {
    id: "7",
    name: "설채현",
    introduction: "안녕하세요. 설채현입니다.",
    profile_img: "/Test-face.png",
    career: "보듬컴퍼니 수의사", // 최종(현재) 커리어
    occupation: OccupationType.VETERINARIAN,
    traning_name: "보듬 훈련소",
    corporation_name: "보듬컴퍼니",
    traning_location: "중랑구 상봉동 104-37",
    corporationId: "5",
    createdAt: new Date("2024-7-23"),
    updatedAt: new Date(),
  },
  {
    id: "8",
    name: "설채현",
    introduction: "안녕하세요. 설채현입니다.",
    profile_img: "/Test-face.png",
    career: "보듬컴퍼니 수의사", // 최종(현재) 커리어
    occupation: OccupationType.VETERINARIAN,
    traning_name: "보듬 훈련소",
    corporation_name: "보듬컴퍼니",
    traning_location: "중랑구 상봉동 104-37",
    corporationId: "6",
    createdAt: new Date("2024-7-23"),
    updatedAt: new Date(),
  },
];

const CorporationData: Corporation[] = [
  {
    id: "1",
    owner_name: "강형욱", // 대표자 이름
    corporation_name: "보듬컴퍼니", // 기업 이름
    address: "중랑구 상봉동 씨티7 202호",
    phoneNumber: "02-3333-33333",
    email: "admin@mubg.ddd",
    business_number: "02-3333-33333", // 사업자번호
    createdAt: new Date("2024-7-23"),
    updatedAt: new Date(),
  },
  {
    id: "2",
    owner_name: "강형욱", // 대표자 이름
    corporation_name: "보듬컴퍼니", // 기업 이름
    address: "중랑구 상봉동 씨티7 202호",
    phoneNumber: "02-3333-33333",
    email: "admin@mubg.ddd",
    business_number: "02-3333-33333", // 사업자번호
    createdAt: new Date("2024-7-23"),
    updatedAt: new Date(),
  },
  {
    id: "3",
    owner_name: "강형욱", // 대표자 이름
    corporation_name: "보듬컴퍼니", // 기업 이름
    address: "중랑구 상봉동 씨티7 202호",
    phoneNumber: "02-3333-33333",
    email: "admin@mubg.ddd",
    business_number: "02-3333-33333", // 사업자번호
    createdAt: new Date("2024-7-23"),
    updatedAt: new Date(),
  },
  {
    id: "4",
    owner_name: "강형욱", // 대표자 이름
    corporation_name: "보듬컴퍼니", // 기업 이름
    address: "중랑구 상봉동 씨티7 202호",
    phoneNumber: "02-3333-33333",
    email: "admin@mubg.ddd",
    business_number: "02-3333-33333", // 사업자번호
    createdAt: new Date("2024-7-23"),
    updatedAt: new Date(),
  },
  {
    id: "5",
    owner_name: "강형욱", // 대표자 이름
    corporation_name: "보듬컴퍼니", // 기업 이름
    address: "중랑구 상봉동 씨티7 202호",
    phoneNumber: "02-3333-33333",
    email: "admin@mubg.ddd",
    business_number: "02-3333-33333", // 사업자번호
    createdAt: new Date("2024-7-23"),
    updatedAt: new Date(),
  },
  {
    id: "6",
    owner_name: "강형욱", // 대표자 이름
    corporation_name: "보듬컴퍼니", // 기업 이름
    address: "중랑구 상봉동 씨티7 202호",
    phoneNumber: "02-3333-33333",
    email: "admin@mubg.ddd",
    business_number: "02-3333-33333", // 사업자번호
    createdAt: new Date("2024-7-23"),
    updatedAt: new Date(),
  },

  {
    id: "7",
    owner_name: "강형욱", // 대표자 이름
    corporation_name: "보듬컴퍼니", // 기업 이름
    address: "중랑구 상봉동 씨티7 202호",
    phoneNumber: "02-3333-33333",
    email: "admin@mubg.ddd",
    business_number: "02-3333-33333", // 사업자번호
    createdAt: new Date("2024-7-23"),
    updatedAt: new Date(),
  },
];

const UserData: User[] = [
  {
    id: "1",
    name: "강형욱", // 대표자 이름
    birthday: new Date("2024-7-23"),
    nickname: "잉잉",
    address: "중랑구 상봉동 씨티7 202호",
    phoneNumber: "02-3333-33333",
    registrationNumber: "0012184357710",
    email: "admin@mubg.ddd",
    gender: GenderType.FEMALE, // 사업자번호
    createdAt: new Date("2024-7-23"),
    updatedAt: new Date(),
  },
  {
    id: "2",
    name: "강형욱", // 대표자 이름
    birthday: new Date("2024-7-23"),
    nickname: "잉잉",
    address: "중랑구 상봉동 씨티7 202호",
    phoneNumber: "02-3333-33333",
    registrationNumber: "0012184357711",
    email: "admin@mubg.ddd",
    gender: GenderType.FEMALE, // 사업자번호
    createdAt: new Date("2024-7-23"),
    updatedAt: new Date(),
  },
  {
    id: "3",
    name: "강형욱", // 대표자 이름
    birthday: new Date("2024-7-23"),
    nickname: "잉잉",
    address: "중랑구 상봉동 씨티7 202호",
    phoneNumber: "02-3333-33333",
    registrationNumber: "0012184357712",
    email: "admin@mubg.ddd",
    gender: GenderType.FEMALE, // 사업자번호
    createdAt: new Date("2024-7-23"),
    updatedAt: new Date(),
  },
  {
    id: "4",
    name: "강형욱", // 대표자 이름
    birthday: new Date("2024-7-23"),
    nickname: "잉잉",
    address: "중랑구 상봉동 씨티7 202호",
    phoneNumber: "02-3333-33333",
    registrationNumber: "0012184357713",
    email: "admin@mubg.ddd",
    gender: GenderType.FEMALE, // 사업자번호
    createdAt: new Date("2024-7-23"),
    updatedAt: new Date(),
  },
  {
    id: "5",
    name: "강형욱", // 대표자 이름
    birthday: new Date("2024-7-23"),
    nickname: "잉잉",
    address: "중랑구 상봉동 씨티7 202호",
    phoneNumber: "02-3333-33333",
    registrationNumber: "0012184357714",
    email: "admin@mubg.ddd",
    gender: GenderType.FEMALE, // 사업자번호
    createdAt: new Date("2024-7-23"),
    updatedAt: new Date(),
  },
  {
    id: "6",
    name: "강형욱", // 대표자 이름
    birthday: new Date("2024-7-23"),
    nickname: "잉잉",
    address: "중랑구 상봉동 씨티7 202호",
    phoneNumber: "02-3333-33333",
    registrationNumber: "0012184357715",
    email: "admin@mubg.ddd",
    gender: GenderType.FEMALE, // 사업자번호
    createdAt: new Date("2024-7-23"),
    updatedAt: new Date(),
  },

  {
    id: "7",
    name: "강형욱", // 대표자 이름
    birthday: new Date("2024-7-23"),
    nickname: "잉잉",
    address: "중랑구 상봉동 씨티7 202호",
    phoneNumber: "02-3333-33333",
    registrationNumber: "0012184357716",
    email: "admin@mubg.ddd",
    gender: GenderType.FEMALE, // 사업자번호
    createdAt: new Date("2024-7-23"),
    updatedAt: new Date(),
  },
];

const AdoptionData: Adoption[] = [
  {
    id: "1",
    adoption_date: new Date("2023-09-11"),
    abandon_date: new Date("2023-12-11"),
    status: AdoptionStatus.ABANDON,
    createdAt: new Date(),
    updatedAt: new Date(),
    userId: "1",
    corporationId: null,
    animalId: "1",
  },
  {
    id: "2",
    adoption_date: new Date("2023-09-11"),
    abandon_date: null,
    status: AdoptionStatus.ADOPTION,
    createdAt: new Date(),
    updatedAt: new Date(),
    userId: "1",
    corporationId: null,
    animalId: "2",
  },
  {
    id: "3",
    adoption_date: new Date("2020-09-11"),
    abandon_date: null,
    status: AdoptionStatus.ADOPTION,
    createdAt: new Date(),
    updatedAt: new Date(),
    userId: "1",
    corporationId: null,
    animalId: "2",
  },
  {
    id: "4",
    adoption_date: new Date(),
    abandon_date: null,
    status: AdoptionStatus.ADOPTION,
    createdAt: new Date(),
    updatedAt: new Date(),
    userId: "5",
    corporationId: null,
    animalId: "3",
  },
];

const AbandonData: Abandon[] = [
  {
    id: "1",
    abandon_date: new Date("2023-09-11"),
    abandon_reason: "그냥",
    adoption_date: new Date("2023-08-11"),
    createdAt: new Date(),
    updatedAt: new Date(),
    userId: "1",
    corporationId: null,
    animalId: "2",
  },
  {
    id: "2",
    abandon_date: new Date("2019-09-11"),
    abandon_reason: "그냥",
    adoption_date: new Date("2023-07-11"),
    createdAt: new Date(),
    updatedAt: new Date(),
    userId: "7",
    corporationId: null,
    animalId: "5",
  },
];

const AnimalData: Animal[] = [
  {
    id: "1",
    name: "미음",
    age: 3,
    gender: GenderType.FEMALE,
    breed: "코카스파니엘",
    profile: "/images/record/dogprofile.png",
    additionalImgs: [],
    createdAt: new Date(),
    updatedAt: new Date(),
    userId: "1",
    corporationId: null,
  },
  {
    id: "2",
    name: "ddddd",
    age: 3,
    gender: GenderType.MALE,
    breed: "코카스파니엘",
    profile: "/images/record/dogprofile.png",
    additionalImgs: [],
    createdAt: new Date(),
    updatedAt: new Date(),
    userId: null,
    corporationId: "1",
  },
  {
    id: "3",
    name: "aa",
    age: 3,
    gender: GenderType.MALE,
    breed: "코카스파니엘",
    profile: "/images/record/dogprofile.png",
    additionalImgs: [],
    createdAt: new Date(),
    updatedAt: new Date(),
    userId: "5",
    corporationId: null,
  },
  {
    id: "4",
    name: "s",
    age: 3,
    gender: GenderType.MALE,
    breed: "코카스파니엘",
    profile: "/images/record/dogprofile.png",
    additionalImgs: [],
    createdAt: new Date(),
    updatedAt: new Date(),
    userId: null,
    corporationId: "2",
  },
  {
    id: "5",
    name: "a",
    age: 3,
    gender: GenderType.MALE,
    breed: "코카스파니엘",
    profile: "/images/record/dogprofile.png",
    additionalImgs: [],
    createdAt: new Date(),
    updatedAt: new Date(),
    userId: null,
    corporationId: "5",
  },
];

const traningCenterData: TraningCenter[] = [
  {
    id: "1",
    name: "송이 훈련소",
    introduction: `안녕하세요. !보듬 훈련소 입니다.
    저는 강형욱 입니다.`,
    profile: "/training-center.png",
    additionalImgs: [
      "/Test-tutor.png",
      "/Test-face.png",
      "/Test-courseImg.png",
    ],
    address: "서울특별시",
    holidays: ["목", "금"],
    price: 50000,
    like: 12,
    createdAt: new Date(),
    updatedAt: new Date(),
    tutorId: "1",
    corporationId: "1",
  },
  {
    id: "2",
    name: "보듬 훈련소",
    introduction: `안녕하세요. !보듬 훈련소 입니다.
    저는 강형욱 입니다.`,
    address: "서울특별시",
    profile: "/training-center.png",
    additionalImgs: [
      "/Test-tutor.png",
      "/Test-face.png",
      "/Test-courseImg.png",
    ],
    holidays: ["목", "금"],
    price: 51000,
    like: 12,
    createdAt: new Date(),
    updatedAt: new Date(),
    tutorId: "2",
    corporationId: "1",
  },
  {
    id: "3",
    name: "보듬 훈련소",
    introduction: `안녕하세요. !보듬 훈련소 입니다.
    저는 강형욱 입니다.`,
    address: "충청북도",
    profile: "/training-center.png",
    additionalImgs: [
      "/Test-tutor.png",
      "/Test-face.png",
      "/Test-courseImg.png",
    ],
    holidays: ["목", "금"],
    price: 60000,
    like: 12,
    createdAt: new Date(),
    updatedAt: new Date(),
    tutorId: "3",
    corporationId: "1",
  },
  {
    id: "4",
    name: "보듬 훈련소",
    introduction: `안녕하세요. !보듬 훈련소 입니다.
    저는 강형욱 입니다.`,
    address: "충청남도",
    profile: "/training-center.png",
    additionalImgs: [
      "/Test-tutor.png",
      "/Test-face.png",
      "/Test-courseImg.png",
    ],
    holidays: ["목", "금"],
    price: 10000,
    like: 12,
    createdAt: new Date(),
    updatedAt: new Date(),
    tutorId: "4",
    corporationId: "1",
  },
  {
    id: "5",
    name: "보듬 훈련소",
    introduction: `안녕하세요. !보듬 훈련소 입니다.
    저는 강형욱 입니다.`,
    address: "경상북도",
    profile: "/training-center.png",
    additionalImgs: [
      "/Test-tutor.png",
      "/Test-face.png",
      "/Test-courseImg.png",
    ],
    holidays: ["목", "금"],
    price: 500,
    like: 12,
    createdAt: new Date(),
    updatedAt: new Date(),
    tutorId: "5",
    corporationId: "1",
  },
];

const reviewData: Review[] = [
  {
    id: "1",
    parentId: null,
    content: "너무 좋아요!!!_#1",
    rating: RatingStatus.VERY_GOOD,
    createdAt: new Date("2024-10-9"),
    updatedAt: new Date(),
    userId: "1",
    traningCenterId: "1",
  },
  {
    id: "2",
    parentId: null,
    content: "너무 좋아요!!!_#2",
    rating: RatingStatus.GOOD,
    createdAt: new Date("2024-01-12"),
    updatedAt: new Date(),
    userId: "2",
    traningCenterId: "1",
  },
  {
    id: "3",
    parentId: null,
    content: "너무 좋아요!!!_#3",
    rating: RatingStatus.GENERAL,
    createdAt: new Date("2024-03-12"),
    updatedAt: new Date(),
    userId: "3",
    traningCenterId: "1",
  },
  {
    id: "4",
    parentId: null,
    content: "너무 좋아요!!!_#4",
    rating: RatingStatus.GENERAL,
    createdAt: new Date("2022-01-12"),
    updatedAt: new Date(),
    userId: "4",
    traningCenterId: "1",
  },
  {
    id: "5",
    parentId: null,
    content: "너무 좋아요!!!_#5",
    rating: RatingStatus.BAD,
    createdAt: new Date("2020-01-12"),
    updatedAt: new Date(),
    userId: "5",
    traningCenterId: "1",
  },
];

export default {
  lectureData,
  curriculumLectureData,
  TutorData,
  CorporationData,
  UserData,
  AdoptionData,
  AbandonData,
  AnimalData,
  userCurriculumData,
  traningCenterData,
  reviewData,
};
